### ISSUE TITLE
Blocking D&D Beyond Content

### ISSUE THREAD

**Issue by OnslaughtDom** [AshDevFr/encounters_app#1]
**Describe the bug**
When I have the app running, no page in D&D Beyond will load - character details, monsters, info from books

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by AshDevFr** [comment]
Hi @OnslaughtDom, are you talking about the Chrome extension?

**Comment by OnslaughtDom** [comment]
Hi @AshDevFr , exactly!

Sorry for being unclear, I'm inexperienced with GitHub

**Comment by AshDevFr** [comment]
Is it happening all the time? 

Are you using the embedded dm screen or the popup?

Could you try to reduce the refresh time if you are using the refresh feature? 
![image](https://user-images.githubusercontent.com/7372540/82153901-2f1c1880-981f-11ea-930b-9b7df0bdc41b.png)

**Comment by OnslaughtDom** [comment]
> Is it happening all the time?
Yes. 
It's been like this for a week.

>Are you using the embedded dm screen or the popup?
Embedded one 

>Could you try to reduce the refresh time if you are using the refresh feature?
I tried to "off" the refresh altogether, but problem persists :(

**Comment by AshDevFr** [comment]
When you disable the extension it's working ?

**Comment by OnslaughtDom** [comment]
> When you disable the extension it's working?
Yes. When I disable everything, I can access D&D Beyond content as  expected.

I also had another friend who had the same issue while we were playing.

>How often were you using the app?
We had two games in the last few days (Tu and Th), and I also had the same issue when doing some prep to next week's game yesterday.

**Comment by AshDevFr** [comment]
DnDBeyond has been restricting the use of third party lately and some users are experiencing issues being asked to verify they are a human. [link](https://www.dndbeyond.com/forums/d-d-beyond-general/bugs-support/56430-constantly-being-asked-to-verify-i-am-a-human) / [link](https://www.dndbeyond.com/forums/d-d-beyond-general/bugs-support/48710-blocking-https-www-dndbeyond-com-character-id-json)

Unfortunately if it's the issue there is really not much I can do.

When you say you disable everything, are you talking about the extension only?

If the extension is not working for you, you can check my other project: https://4sh.dev/d-d-toolbox/ It does have a DM screen but no auto refresh.

**Comment by OnslaughtDom** [comment]
>DnDBeyond has been restricting the use of third party lately and some users are experiencing issues being asked to verify they are a human. link / link
Never got one of those, thankfully!

It's sad because those third party developments complement D&D Beyond's tools with much needed features, like yours DM Screen, that's in the "why it took so long for someone to do this" field.

> When you say you disable everything, are you talking about the extension only?
I flag "off" both "Autoload embedded screen:" and "Refresh:"

**Comment by AshDevFr** [comment]
Would you mind taking a look at the chrome console to see if there are some error messages. 
[Open the devtools](https://developers.google.com/web/tools/chrome-devtools/open), then in the `Console` tab you will be able to see the errors. ([Console overview](https://developers.google.com/web/tools/chrome-devtools/console)).

Reload the page and look at the red messages. If you see some, could you send them here please?

**Comment by OnslaughtDom** [comment]
Here it is:

[Console.docx](https://github.com/AshDevFr/encounters_app/files/4641207/Console.docx)

**Comment by AshDevFr** [comment]
I don't see errors related to the extension. Could you try to [load the extension in incognito mode](https://lifehacker.com/enable-your-extensions-in-incognito-mode-for-safer-mor-1792622065) so it will run without your other extensions. Then send the console screenshot. 

Just a screenshot will be fine, you don't need to send a `.docx` file.
