### ISSUE TITLE
Unable to delete campaign

### ISSUE THREAD

**Issue by Price454** [AshDevFr/encounters_app#2]
**Describe the bug**
I am unable to delete characters or campaigns from the app.
I don't know if this is implemented or not, but the feature is not on the list on the homepage.

**To Reproduce**
1. Go to 'campaigns'
2. Click on 'trash bucket icon'
Alternatively,
1. Go to 'campaigns'
2. Remove characters from the campaign beforehand:
2.1. Click on the 'Add / Remove characters' icon
2.2. Toggle radio buttons to 'OFF' for all characters
3. Click on the 'Delete' icon

**Expected behavior**
Able to delete the campaign

**Screenshots**
Non-applicable

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 75.0

**Comment by AshDevFr** [comment]
Hi @Price454 , thank you for the bug report. You should be able to do that. 
I will check.

**Comment by AshDevFr** [comment]
Hi @Price454, I pushed a fix, please try again

**Comment by Price454** [comment]
Confirmed, fixed.
