### ISSUE TITLE
Unable to delete character

### ISSUE THREAD

**Issue by Price454** [AshDevFr/encounters_app#3]
**Describe the bug**
I am unable to delete characters from the app.
I don't know if this is implemented or not, but the feature is not on the list on the homepage.

**To Reproduce**
1. Go to 'Characters'
2. Click on 'trash bucket icon'
3. Notify the 'not_found' toast message is displayed

**Expected behavior**
Able to delete the characters

**Screenshots**
Non-applicable

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 75.0

**Comment by AshDevFr** [comment]
Hi @Price454 , thank you for the bug report. You should be able to do that. 
I will check.

**Comment by AshDevFr** [comment]
Hi @Price454, I pushed a fix, please try again

**Comment by Price454** [comment]
Confirmed, fixed.
