### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by acbcine** [AshDevFr/encounters_app#6]
**Describe the bug**
The stats aren't showing up

**To Reproduce**
1. Activate the D&D Beyond Campaign DM Screen
2. View any of my campaigns
3. Nothing happens

**Expected behavior**
It works.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
I wish it worked.

**Comment by AshDevFr** [comment]
Hi, the bug was caused by a change made by the dndbeyond team. I deployed a fix yesterday night. Please take a look (v1.2.0 of the extension).
Closing this issue. Feel free to create a new one if it is still failing with the new version.

**Comment by acbcine** [comment]
Thank you! It works!!
