### ISSUE TITLE
Missing Characterrs

### ISSUE THREAD

**Issue by Confused-Banana** [AshDevFr/encounters_app#9]
Two of six characters are shown in the DM view and are included in the popup window. 

Open Campaign.
(Only two characters have extended layout.)
Click on "DM Screen"
(The same two characters are shown here.)

**Expected behavior**
All characters have an extended layout and are in the popup.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 1.2.1

![Capture](https://user-images.githubusercontent.com/67517914/85929124-ec1a7f80-b877-11ea-8e9a-e93f88aece2d.PNG)
![Capture1](https://user-images.githubusercontent.com/67517914/85929135-f472ba80-b877-11ea-8c7b-d23779544ed2.PNG)

**Comment by AshDevFr** [comment]
Hi @Confused-Banana, would you mind taking a look at the chrome console to see if there are some error messages. 
[Open the devtools](https://developers.google.com/web/tools/chrome-devtools/open), then in the `Console` tab you will be able to see the errors. ([Console overview](https://developers.google.com/web/tools/chrome-devtools/console)).

Reload the page and look at the red messages. If you see some, could you send them here please?

**Comment by Confused-Banana** [comment]
![Capture](https://user-images.githubusercontent.com/67517914/87880769-ff71c400-c9b9-11ea-9c6e-0ec184a7a768.PNG)

**Comment by AshDevFr** [comment]
`403` means you don't have access to this character.
When I try to go on https://character-service.dndbeyond.com/character/v3/character/29271619 I also get a `403` error

If I go on https://www.dndbeyond.com/characters/29271619 it says the character is not found. Are you sure the characters in your list still exists? 
I only tried one of them but I am not sure why this character is missing. It could be `private`. Is there anything specific to it ?

Do you have access to all of the character sheets ?

**Comment by Confused-Banana** [comment]
I can view and edit all of the sheets. I think most, if not all of them, are set to private. The first time I ran the extension it worked for all of my players. Now it only shows the two. I'm not sure what has changed.

**Comment by AshDevFr** [comment]
DndBeyond has change the APIs so we cannot use the old way anymore. 
For the extension to work, characters have to be set not to `private`.

**Comment by Confused-Banana** [comment]
okay, thanks! I will let my players know. Thank you!
